import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "../components/Navigation";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dark Ace Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Navigation />
        <h1>Dark Ace Admin</h1>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
